// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StarGate.Data;

#nullable disable

namespace StarGate.Data.Migrations
{
    [DbContext(typeof(StarGateDbContext))]
    [Migration("20230226031829_AddUniqueCodesToModelsMigration")]
    partial class AddUniqueCodesToModelsMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("StarGate.Data.Models.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Symbol1Id")
                        .HasColumnType("int");

                    b.Property<int>("Symbol2Id")
                        .HasColumnType("int");

                    b.Property<int>("Symbol3Id")
                        .HasColumnType("int");

                    b.Property<int>("Symbol4Id")
                        .HasColumnType("int");

                    b.Property<int>("Symbol5Id")
                        .HasColumnType("int");

                    b.Property<int>("Symbol6Id")
                        .HasColumnType("int");

                    b.Property<int>("Symbol7Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Symbol1Id");

                    b.HasIndex("Symbol2Id");

                    b.HasIndex("Symbol3Id");

                    b.HasIndex("Symbol4Id");

                    b.HasIndex("Symbol5Id");

                    b.HasIndex("Symbol6Id");

                    b.HasIndex("Symbol7Id");

                    b.ToTable("Address");
                });

            modelBuilder.Entity("StarGate.Data.Models.Planet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("Explored")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("Safety")
                        .HasColumnType("int");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("TeamId");

                    b.ToTable("Planet");
                });

            modelBuilder.Entity("StarGate.Data.Models.Request", b =>
                {
                    b.Property<int>("PlanetId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasIndex("PlanetId");

                    b.ToTable("Request");
                });

            modelBuilder.Entity("StarGate.Data.Models.Symbol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<byte[]>("Image")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Symbol");
                });

            modelBuilder.Entity("StarGate.Data.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Members")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Team");
                });

            modelBuilder.Entity("StarGate.Data.Models.Address", b =>
                {
                    b.HasOne("StarGate.Data.Models.Symbol", "Symbol1")
                        .WithMany()
                        .HasForeignKey("Symbol1Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StarGate.Data.Models.Symbol", "Symbol2")
                        .WithMany()
                        .HasForeignKey("Symbol2Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StarGate.Data.Models.Symbol", "Symbol3")
                        .WithMany()
                        .HasForeignKey("Symbol3Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StarGate.Data.Models.Symbol", "Symbol4")
                        .WithMany()
                        .HasForeignKey("Symbol4Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StarGate.Data.Models.Symbol", "Symbol5")
                        .WithMany()
                        .HasForeignKey("Symbol5Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StarGate.Data.Models.Symbol", "Symbol6")
                        .WithMany()
                        .HasForeignKey("Symbol6Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StarGate.Data.Models.Symbol", "Symbol7")
                        .WithMany()
                        .HasForeignKey("Symbol7Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Symbol1");

                    b.Navigation("Symbol2");

                    b.Navigation("Symbol3");

                    b.Navigation("Symbol4");

                    b.Navigation("Symbol5");

                    b.Navigation("Symbol6");

                    b.Navigation("Symbol7");
                });

            modelBuilder.Entity("StarGate.Data.Models.Planet", b =>
                {
                    b.HasOne("StarGate.Data.Models.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StarGate.Data.Models.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("StarGate.Data.Models.Request", b =>
                {
                    b.HasOne("StarGate.Data.Models.Planet", "Planet")
                        .WithMany()
                        .HasForeignKey("PlanetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Planet");
                });
#pragma warning restore 612, 618
        }
    }
}
